// #define IGNORE_MOD_TAP_INTERRUPT
#define RETRO_TAPPING
#define TAPPING_TERM 200

#define TAPPING_TOGGLE 3

#define COMBO_VARIABLE_LEN 
#define COMBO_TERM 25

#define MK_COMBINED

#define ENCODER_DIRECTION_FLIP
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

// Leader Key
#define LEADER_TIMEOUT             400 // was 900
#define LEADER_PER_KEY_TIMING      200 // was 300

// Mouse key speed and acceleration.
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       16
#undef MOUSEKEY_WHEEL_MAX_SPEED 
#define MOUSEKEY_WHEEL_MAX_SPEED 16
#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 40
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      4 // was 6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    64
